### PR TITLE
💄 Use latest brand wordmark

### PR DESCRIPTION
**Pull request by olyism**
Replace word mark "Buildkite Docs" in page and homepage header with the brand's font.

To avoid loading an entire font file, I've decided to use the SVG image instead, following the same treatment as the marketing site.

Screen Shot 2022-08-15 at 10 00 41 pm

Screen Shot 2022-08-15 at 10 00 55 pm

### CODE REVIEW

**Comment by olyism** [comment]
Note that SVGs are a bit pixelate in Chrome. Safari's a lot smoother. 

There are some ways to make it look nicer in Chrome but too hack-y + too much effort.

Screen Shot 2022-08-15 at 10 02 45 pm
Left Chrome, right Safari

Screen Shot 2022-08-15 at 10 03 22 pm
Left Chrome, right Safari

**Review by plaindocs — COMMENTED** [review]
Looks good to me!

**Comment by olyism** [comment]
cool thanks @plaindocs just need an approval and I can merge + test :)

**Review by plaindocs — APPROVED** [review]

**Comment by olyism** [comment]
Thanks @plaindocs for the speedy review. Deployed, tested in the popular browsers ✅

**Pull request merged**
