### PR TITLE
Add Google Analytics tracking

### PR DESCRIPTION
**Pull request by toolmantim**

### CODE REVIEW

**Comment by plaindocs** [comment]
Nice. Are we ripping Posthog and Matomo out as well?

**Comment by toolmantim** [comment]
Yep, that'd be next stage @plaindocs!

**Comment by toolmantim** [comment]
@scopegate @lachlanhardy is this good to merge?

**Comment by lachlanhardy** [comment]
Sure. I thought I approved this already?

On Thu, May 27, 2021 at 8:45 PM, Tim Lucas ***@***.***> wrote:


@scopegate [https://github.com/scopegate] @lachlanhardy [https://github.com/lachlanhardy] is this good to merge?

**Pull request merged**
