### PR TITLE
Import Emojicom feedback to Linear

### PR DESCRIPTION
**Pull request by plaindocs**
This is pretty basic but it works. 
Sadly the linear import cli doesn't take arguments. :-/

### CODE REVIEW

**Review by karensawrey — APPROVED** [review]
YOLO Friday deploy.

**Comment by plaindocs** [comment]
I mean, this isn't really a deploy, the script only runs locally. :-D

I might see if @lachlanhardy can suggest any improvements to this before we merge it.

**Comment by lachlanhardy** [comment]
If you want to get more idiomatic about your Ruby, I asked Elle to help me with a rough untested refactor into Ruby idiom:

```
require 'csv'

class GrabComments
  RATINGS_FILE_PATH = "#{Dir.home}/Downloads/ratings-export.csv"
  OUTPUT_FILE_PATH = __dir__+'/linear.csv'
  PROCESSED_RATING_PATH = __dir__+'/emojicom-processed-ratings.txt'

  def self.run
    new.run
  end

  def run
    unless rating_file_exists?
      puts "Download the ratings from https://emojicom.io before running this script"
      return
    end

    CSV.foreach(RATINGS_FILE_PATH, force_quotes: true, headers: true, liberal_parsing: true) do |row|
      unless processed_comments.include?(row[0]) && row[5].to_s.empty?
        output = CSV.open(OUTPUT_FILE_PATH, "a", quote_empty: true, force_quotes: true) do |line|
          desc = row[5] + "\n\nCreated at: " + row[1] + "\nID: " + row[0] + "\nEmail: " +row[6].to_s  + "\nPage: " + row[7].to_s
          line << [row[5].split[0..10].join(' '), desc, "Low", "Todo", "", "Feedback"]

          # Log the comment we just output
          File.write(PROCESSED_RATING_PATH, row[0]+"\n", mode: "a")

        end
      end
    end

    File.delete(RATINGS_FILE_PATH)
  end

  private

  def rating_file_exists?
    File.exist?(RATINGS_FILE_PATH)
  end

  def write_csv_headings
    @output = CSV.open(OUTPUT_FILE_PATH, "wb") do |line|
      line << ["Title", "Description", "Priority", "Status", "Assignee", "Labels"]
    end
  end

  def processed_comments
    @processed_comments = File.read(PROCESSED_RATING_PATH).split
  end
end


GrabComments.run
```

It needs more refactoring and hasn't been tested locally so wholesale replacement might not work immediately but it's illustrative of style.

**Comment by plaindocs** [comment]
Cheers mate, I'll merge this for now - but the difference is helpful <3

**Pull request merged**
