### PR TITLE
🔍 Consistent "Agent, Plugin" ordering

### PR DESCRIPTION
**Pull request by drnic**
I feel the need to apologise for this anally retentive fix.

### CODE REVIEW

**Comment by keithpitt** [comment]
Good find :)

**Comment by toolmantim** [comment]
I have a strong suspicion that the original docs might been accurate:
https://github.com/buildkite/agent/blob/master/bootstrap/bootstrap.go#L889

**Comment by harrietgrace** [comment]
Sorry @drnic, I'm going to have to revert this one! That column has specific ordering, so it was the original way around on purpose. Thanks for the PR though, we always love contributions 😄

**Comment by keithpitt** [comment]
Oh, doh! My bad!

**Comment by drnic** [comment]
Thanks. I learned a thing.

**Pull request merged**
