### PR TITLE
Correct hidden text display error for navicon

### PR DESCRIPTION
**Pull request by lachlanhardy**
Fixing display error created in https://github.com/buildkite/docs/pull/1306

### CODE REVIEW

**Comment by lachlanhardy** [comment]
This has been fixed and is building now: https://buildkite.com/buildkite/docs/builds/2115

@chrislloyd Thanks so much for letting me know.

**Comment by chrislloyd** [comment]
Quick turnaround!

Hope everything is well with you ☺️

**Comment by lachlanhardy** [comment]
Fix is live in production.

**Comment by lachlanhardy** [comment]
Nothing like a little production patch to wake you up in the morning!

**Comment by plaindocs** [comment]
Thanks so much for spotting @chrislloyd and for fixing so fast @lachlanhardy <3

**Pull request merged**
