### PR TITLE
Update GitHub enterprise guide

### LINKED ISSUE #307: Update "GitHub Enterprise" page
Hi Buildkite Team,

A couple of days ago I integrated Buildkite with GitHub Enterprise 2.13.5 and found out that the instructions in the section [Register Buildkite as a new application](https://buildkite.com/docs/integrations/github-enterprise#register-buildkite-as-a-new-application) could be updated. At least, GitHub Enterprise 2.13.5 UI was a bit different from described in the instructions above. 

In GitHub Enterprise 2.13.5 I had to:
1. Navigate to "Settings" (in the dropdown menu in the top right corner) -> "Developer settings" (in the left hand side menu)
2. Select "OAuth Apps" in the left hand side menu
3. Click "New OAuth App" button in the top right corner
4. Complete the form ("Application name", "Homepage URL", Application description", "Authorization callback URL")
screen shot 2018-08-30 at 8 09 42 pm
5. Hit "Register application" button.

The last two section I followed were:
1. [Update your Buildkite organization settings](https://buildkite.com/docs/integrations/github-enterprise#update-your-buildkite-organization-settings)
2. [Connect your GitHub Enterprise account](https://buildkite.com/docs/integrations/github-enterprise#connect-your-github-enterprise-account)

They were absolutely correct and up to date.

Now Buildkite shows "GitHub Enterprise Webhook Setup" page when a new pipeline is created. 

Please let me know if you need additional information.

Thanks a lot for the great tool and support. Specifically, I would like to thank @keithpitt for his quick replies and instructions.

### PR DESCRIPTION
**Pull request by harrietgrace**
First cut of the updates to the github enterprise guide. I think it's mostly there, but I think I need to re-do some of the new images. 

Todo:
- [x] Fix up wonky screenshots
- [x] Check that the callback url is the same and works
- [x] Test full setup flow again

Closes #307

### CODE REVIEW

**Comment by harrietgrace** [comment]
@keithpitt is the GitHub enterprise callback URL still the same? (https://buildkite.com/user/authorize/github_enterprise/callback) 

I tried to do the 'connected apps' connect bit and when GitHub tried to redirect there after authorising, I got the 'buildkite has had a problem' page.

**Comment by keithpitt** [comment]
@harrietgrace oh, boo. Yeah - it should still be the same! Ping me when you're online and have a few minutes to Zoom and pair on what's going on.

**Comment by harrietgrace** [comment]
@keithpitt helped me figure out what was going on - it was just that we don't accept self-signed certs when connecting to an app like github. I've posted a message about it in Basecamp.

The rest of the guide is sorted, ready for a quick review @toolmantim!

**Comment by harrietgrace** [comment]
All of them except the one I fixed up the other day are already optim'd 😬 Do you think they need to be smaller? 

image

**Comment by toolmantim** [comment]
Nice 👌🏼

Hrmm in general they do seem quite big, 0.5MB of images in total? They must just be large dimensions. One day we’ll have some automatic webp format generation, or an auto-optimizing CDN.

Let’s 🚀🚀🚀

**Pull request merged**
