### PR TITLE
📝 Styleguide for responsive table

### PR DESCRIPTION
**Pull request by olyism**
Add instructions on adding responsive table.

### CODE REVIEW

**Review by lachlanhardy — APPROVED** [review]
🚀

**Comment by olyism** [comment]
Thanks @lachlanhardy for the review.

@karensawrey I'll hold on merging, be keen to get your thoughts on the language that I used.

**Review by karensawrey — APPROVED** [review]

**Comment by karensawrey** [comment]
Awesome addition to the style guide, @olyism! I merged in 2 tiny improvements. Please ship the whole thing when the tests pass. 👍

**Comment by karensawrey** [comment]
Ship it! 🚢🚢 🚢  ;)

**Pull request merged**
