### PR TITLE
Bazel

### PR DESCRIPTION
**Pull request by plaindocs**
This is currently mostly just the steps I took to get a working build using bazel. 

We should decide if we're going to use the C++ tutorial or host our own.

### CODE REVIEW

**Comment by yob** [comment]
The error page in the preview app is triggered by the follow error in the logs:

```
2020-04-09T11:58:18.721443+00:00 app[web.1]: Sprockets::Rails::Helper::AssetNotFound (The asset "tutorials/bazel/add-to-bazel" is not present in the asset pipeline.):
2020-04-09T11:58:18.721499+00:00 app[web.1]:   
2020-04-09T11:58:18.721535+00:00 app[web.1]: app/models/page.rb:43:in `image_url'
2020-04-09T11:58:18.721535+00:00 app[web.1]: app/models/page.rb:28:in `image'
2020-04-09T11:58:18.721536+00:00 app[web.1]: (erb):49:in `get_binding'
2020-04-09T11:58:18.721536+00:00 app[web.1]: app/models/page.rb:105:in `body'
2020-04-09T11:58:18.721537+00:00 app[web.1]: app/controllers/pages_controller.rb:15:in `show'
```

**Comment by plaindocs** [comment]
My mistake again, thanks for fixing @yob.

**Comment by plaindocs** [comment]
@toolmantim could you take a look at the codeblock inside lists?

**Comment by toolmantim** [comment]
Ah, I booted this up this branch and started digging in, thinking I should get that issue looked at today… I'd started on it… but turns out it's no longer necessary 🙌🏼

(I didn't get a notification for the above comment edit tho)

**Comment by toolmantim** [comment]
It's looking pretty great to me! Wanna request a review?

**Pull request merged**
