### PR TITLE
Add possible values for BUILDKITE_S3_ACL

### PR DESCRIPTION
**Pull request by plaindocs**
Fix for #709

### CODE REVIEW

**Comment by harrietgrace** [comment]
Nice! It would be good to add something about there being many options for that value in here too: https://buildkite.com/docs/agent/v3/cli-artifact#using-your-private-aws-s3-bucket

**Comment by plaindocs** [comment]
This is waiting on #708 for the H3 link.

**Comment by harrietgrace** [comment]
I think the underscores in the link to the env var docs need to be escaped, we're getting some funky styling 😅

image

There's a bit of prior art for lists of values, do you think we could do this for the ACL one too? And we could have a `Default:` line for `public-read` too.

image

**Comment by plaindocs** [comment]
Two great catches, thanks @harrietgrace 

I'm not :100: sure what is going on with the underscores, but escaping fixes it, so :man_shrugging:

**Pull request merged**
