### PR TITLE
New way to show buildkite dashboard - buildreactor

### PR DESCRIPTION
**Pull request by SydOps**

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks for this @SydOps! Now that BuildReactor supports Buildkite

**Comment by SydOps** [comment]
Thanks @toolmantim to merge my PR.

The reason why I put detail steps is, maybe end users don't know to use `CCTray Generic` to set Buildkite dashboard. It is not straightforward if go through that link you provided.

**Comment by toolmantim** [comment]
@SydOps BuildReactor just released a new version, that has Buildkite built in. Unfortunately the website hasn't been updated yet though, but it should be simple enough once you're in the BuildReactor settings.

**Comment by SydOps** [comment]
yeah, I saw the updates, that's really nice.

**Comment by SydOps** [comment]
@toolmantim 

I can't make it work with new the serviceType `Buildkite`. The toke is same I used in `CCTray Generic`

screen shot 2017-05-19 at 9 41 24 am

**Comment by toolmantim** [comment]
You might need to check the scopes here? https://github.com/AdamNowotny/BuildReactor/releases/tag/v1.0.0

**Comment by SydOps** [comment]
@toolmantim 

Thanks. All fine now, only token is needed.

**Comment by SydOps** [comment]
@toolmantim 

Did you see this error? https://github.com/AdamNowotny/BuildReactor/issues/67

**Comment by toolmantim** [comment]
@SydOps no I did not! Let me know if there's something on our end that needs fixing.

**Pull request merged**
