### PR TITLE
Fix the emoji rendering on the new Emojis page

### PR DESCRIPTION
**Pull request by toolmantim**
This fixes the Emojis page so it's rendering the new(ish) emojis from the updated submodule.

### CODE REVIEW

**Comment by ticky** [comment]
aahhh I’ve been really trying to fight the “emojis” name, it’s not a good plural of it! can we keep it as emoji everywhere we mention it? the one thing that’s been left is the emoji repo name

**Comment by toolmantim** [comment]
Ah, the emoji/emojis change was included in here because I was on a call with @plaindocs when we were doing this.

Maybe we do in fact just go with "Emoji" @plaindocs @harrietgrace? Do we know from search what customers are using to refer to it?

**Comment by plaindocs** [comment]
Algolia search logs have an appalling data retention policy. Recent searches are for `emoji` not `emojis`. I don't know how much that has to do with intentionally searching for a term that covers both.

**Comment by toolmantim** [comment]
Sounds like emoji it is!

**Pull request merged**
