### PR TITLE
Updated documentation for branch filtering, bang branch name needs to…

### PR DESCRIPTION
**Pull request by justinhennessy**
… use quotes

### CODE REVIEW

**Comment by keithpitt** [comment]
Thanks for the PR! If you define the branch config via the Buildkite UI, you don't need quotes, so we may need to tweak the text here to make that clear :) But we can do that!

**Comment by justinhennessy** [comment]
Of course, so would a (needs quotes if uploading a pipeline via `buildkite-agent pipeline upload`)?

**Comment by keithpitt** [comment]
Yeah, that works :)

**Comment by justinhennessy** [comment]
Done!

**Comment by keithpitt** [comment]
Thanks!

**Pull request merged**
