### PR TITLE
Removing beta pills from TA (sidebar & homepage)

### PR DESCRIPTION
**Pull request by karensawrey**

### CODE REVIEW

**Comment by karensawrey** [comment]
Yay, this absolutely works.

**Review by meiqimichelle — APPROVED** [review]
Lookin' ✨✨✨

Gonna approve as it does what it says on the tin -- dropped a few questions in Basecamp chat but I think they're not related to this review.

**Comment by karensawrey** [comment]
Ready for merge in case someone needs to merge this from a vastly different time zone 👍

**Review by plaindocs — APPROVED** [review]
Looks good to me.

**Pull request merged**
