### PR TITLE
Security guide updates for v3

### PR DESCRIPTION
**Pull request by keithpitt**

### CODE REVIEW

**Comment by keithpitt** [comment]
I'd really like to write some words about what the ramifications of turning it off are, and what the ramifications of having it on by default are.

Do you think that'd be OK to add? Or do you think this guide assumes that they're experts on this stuff?

**Comment by harrietgrace** [comment]
I think that would be really useful, I'm sure there will be plenty of non-experts reading this doc. And it would be a good refresher for experts anyway 😄

**Comment by lox** [comment]
Yup, this is awesome. 

Is it worth explaining some of the why? E.g.

> Automatically scanning keys for ssh hosts uses a "trust on first use" model, which is generally the approach that git/ssh takes. Unfortunately in environments where hosts are being added and removed frequently, there are more opportunities for man-in-the-middle attacks to intercept these requests and modify the response. If this is a concern for your use-case, this feature lets you manage it yourself.

**Comment by lox** [comment]
Beyond that, GitHub publishes their key fingerprints:

https://help.github.com/articles/github-s-ssh-key-fingerprints/

If I were using the `no-ssh-keyscan` feature, I'd probably have an `authorized_hosts` file setup with those fingerprints hardcoded into it.

**Comment by keithpitt** [comment]
(I did a sneaky deal with @lox where I did some data analysis for him and he'll take over this PR and finish the SSH keyscan docs :P)

**Comment by harrietgrace** [comment]
@keithpitt I think this is ready to go?

**Comment by lox** [comment]
I said I'd write some more words for it, but let's get this merged and then I will follow up if we have time.

**Comment by harrietgrace** [comment]
@lox I added in the extra bits that keith requested, was there more on top of that?

**Pull request merged**
