### PR TITLE
Rspec speed

### PR DESCRIPTION
**Pull request by lachlanhardy**

### CODE REVIEW

**Comment by plaindocs** [comment]
This is why the preview is broken

```
❯ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index c159b9dc..1e734d34 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -64,6 +64,7 @@ GEM
     matrix (0.4.2)
     method_source (1.0.0)
     mini_mime (1.1.2)
+    mini_portile2 (2.8.0)
     minitest (5.15.0)
     nio4r (2.5.8)
     nokogiri (1.13.3)
```
Possibly, `mini_portile2` was an unintentional addition?

**Comment by plaindocs** [comment]
Definitely some improvement: ** Total Job Run Time: 7m 53s**

**Comment by plaindocs** [comment]
The missing script is in that environment variable PR we reverted.

**Comment by lachlanhardy** [comment]
@plaindocs Yeah, seems like this branch has served no purpose in comparison to the infrastructure changes.

Shall we ditch it?

**Pull request closed without merging**
