### PR TITLE
Alpha-sort agent configuration setting table + add 'required?' column

### PR DESCRIPTION
**Pull request by petemounce**
I find docs easier to read when sorted. Unfortunately:
* this splits apart the semantic-groupings for things like paths
* this makes token last, but it's required, so I added a column to denote that fact

Suggestion - JS-based table-sorting/filtering thing?

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks @petemounce! We'll check this out.

**Comment by harrietgrace** [comment]
Yay sorting! I find these tables way better when they're alphabetised too 😄
To bring this doc in line with our other tables, rather than add an extra column, we could split it out into required/optional like we do in our [Step Type docs](https://buildkite.com/docs/pipelines/command-step)?

**Comment by petemounce** [comment]
@harrietgrace I thought about that and elected to not, because the effect of the sorting is to make `token` (a required attribute) nowhere near the first thing a reader sees, and so the possibility of their not noticing is much higher I thought.

Making a separate column allows that information to be more obviously distinct to a reader, and also makes it easier to add some client-side table plugin at some point that allows filtering/sorting.

**Comment by harrietgrace** [comment]
I'll do the table update - I'll add a commit to your branch before we merge, if that's alright @petemounce?

**Comment by petemounce** [comment]
Please feel free!

**Pull request merged**
