### PR TITLE
🏳️‍🌈 Show the Philly Pride colors in June

### PR DESCRIPTION
**Pull request by olyism**
Show the Pride color variant of our logo during June.

This is a simple implementation as Pride month is June in The United States, and this is generally acknowledged around the world even if jurisdictions have their own dates.

Screen Shot 2022-06-09 at 10 16 07 pm

Screen Shot 2022-06-09 at 11 22 50 pm

### CODE REVIEW

**Comment by karensawrey** [comment]
Yay! Let's absolutely use the Philly Pride logo for June! I wonder if it's decidedly different from the one used in the Dashboard? 
pride-logo

**Comment by olyism** [comment]
@karensawrey good pick up 👀 ✨

So I went with the simpler design due to the logo size (see @scopegate's [suggestion](https://github.com/buildkite/buildkite/pull/5060#issuecomment-637914237))

Actually, come to think of it… the homepage logo should use the more complex design.

I'll push up another commit to address this soon.

**Comment by olyism** [comment]
Also it doesn't seem like the preview has picked up the date. I assume the production site should have the correct datetime set?

I'll have a quick dig around. If not, then I'll have to lean on client-side JavaScript.

**Comment by olyism** [comment]
Ok, I've made the fixes, git squashed and force pushed everything in one commit. 

- [x] Use the latest Philly Pride flag image
- [x] Use `DateTime` and not `Date` (Ruby rookie mistake)

Ready for review again.

Screen Shot 2022-06-10 at 12 18 49 pm

Screen Shot 2022-06-10 at 12 19 01 pm

**Review by lachlanhardy — APPROVED** [review]
Neatly done.

**Review by karensawrey — APPROVED** [review]
Love it!

**Pull request merged**
