### PR TITLE
Add section to Test Analytics docs for permissions

### PR DESCRIPTION
**Pull request by meiqimichelle**
This PR adds basic information about using Buildkite permissions to manage Test Analytics access.

### CODE REVIEW

**Comment by karensawrey** [comment]
@meiqimichelle I have a strong fear we are going to have a merge conflict of a lifetime soon because of https://github.com/buildkite/docs/pull/1486 :D

**Comment by meiqimichelle** [comment]
@karensawrey 😬😬😬😬😬 but also, happy to use this PR for review, and then copy-and-paste into a new PR based on your EPIC restructure. This should only be one page, or a bit if info to place into other pages.

**Comment by karensawrey** [comment]
> and then copy-and-paste into a new PR based on your EPIC restructure
No need for you to do it @meiqimichelle as it's already pre-planned that once my changes from #1486 are merged in, I'm going to start a new one based on it & copy and paste https://github.com/buildkite/docs/pull/1478 into it. So I guess, I'll just also copy and paste stuff from here into that new PR, too. Plz ping me once you've getting a thumbs up from @plaindocs on this one. Thanks!

**Review by plaindocs — APPROVED** [review]
I think we might want to revisit this for clarity another time, but I'm happy to merge it in for now. CC @karensawrey

**Comment by meiqimichelle** [comment]
Just triple-checking -- I should NOT merge this one outright, because @karensawrey is going to transfer this info somewhere else (and then we'll close this PR)?

**Comment by karensawrey** [comment]
@meiqimichelle go ahead and merge it - I'll pull in your changes into my PR that @plaindocs is yet to review.

**Pull request merged**
