### PR TITLE
🚸 Homepage Elastic CI section

### PR DESCRIPTION
**Pull request by olyism**
Add an Elastic CI section to the homepage. This raises the awareness that we provide Elastic CI Stack and makes it easier for customer to find the content.

Content-wise, I've made the following simplification:

- [x] Removed more links, as these are dupes of the heading link
- [x] Reduced links in the top product sections, especially Pipelines as there are many dupes in the how-to guides
- [x] Top Pipelines tile becomes the Getting Started tile
- [x] Shrunk section headings

Made the following aesthetic and UX improvements:

- [x] Box border tiles for easier eye tracking. better alignment and visual grouping
- [x] Icon hover effects
- [x] Added call-to-action buttons to give products more prominence
- [x] Max width for the homepage to constrain page width on extra large screens

## Screenshot

image

image

### CODE REVIEW

**Comment by plaindocs** [comment]
Oh, I **really** like this! Nice icons, nice boxes. 

My only tiny bikeshed is the little arrows look a little off, especially on the titles. 
They move slightly oddly IMO. But maybe we don't need them at all on the titles?

**Comment by olyism** [comment]
> My only tiny bikeshed is the little arrows look a little off, especially on the titles.
They move slightly oddly IMO. But maybe we don't need them at all on the titles?

Done ✅  This would actually make the markup and CSS simpler ✨

**Comment by olyism** [comment]
Tested on my local machine:

- [x] Chrome
- [x] Safari
- [x] Firefox

## Chrome

Screen Shot 2022-07-07 at 1 59 37 am

Screen Shot 2022-07-07 at 2 00 33 am

## Safari

Screen Shot 2022-07-07 at 2 00 56 am

Screen Shot 2022-07-07 at 2 01 36 am

## Firefox

Screen Shot 2022-07-07 at 2 02 08 am

Screen Shot 2022-07-07 at 2 02 35 am

**Comment by olyism** [comment]
As a UI side note, the homepage now has a `max-width` page container, but it doesn't apply to other pages.

The plan is to have consistent page containers. Trying to keep this PR to scope so will address other pages in another ticket.

**Review by plaindocs — APPROVED** [review]
LGTM

**Pull request merged**
