### PR TITLE
✨ Add emojicom rating and footer styling changes

### PR DESCRIPTION
**Pull request by olyism**
Embed [emojicom](https://emojicom.io) to footer. This allows us to collect feedback respective to the page.

I've also made styling changes to the footer, as well as improvements to existing components affected to this change, so that emojicom can better fit within our layout.

- [x] Embed emojicom script
- [x] Styling
  - [x] Emojicom position
  - [x] Gracefully fallback after it's been rated
  - [x] Style and test other components affected by styling improvements
- [x] Conditionally use a different campaign ID depending on the environment (note: Render previews are currently considered as Production)
- [x] Add ability to turn off on certain pages
- [ ] Investigate if we could load the Development emoji campaign ID for preview site as well

### emojicom loaded

Screen Shot 2022-06-29 at 2 44 38 pm

Screen Shot 2022-06-29 at 2 44 15 pm

### emojicom not loaded

This happens when the customer has already rated so emojicom won't appear. I've changed the design so this falls back gracefully.

Screen Shot 2022-06-29 at 2 46 12 pm

### CODE REVIEW

**Comment by plaindocs** [comment]
@olyism can we turn it off for the landing page? Should we have an option like for the toc?

**Review by lachlanhardy — APPROVED** [review]
Looks great!

I'm not sure about it on the homepage, but that's easy to exclude if others feel the same.

**Review by karensawrey — APPROVED** [review]
Not a review comment per se, but I'm after something more like "Something's missing in the docs?" before "Open an issue/Contribute an update". I see how this can discourage people from leaving feedback, too, but I don't know yet how to word THE ultimate CTA here, hence I'm approving the PR now :)

**Comment by olyism** [comment]
hi @lachlanhardy @plaindocs I've added a logic to remove Emojicom from landing pages, which you can specify within the `LandingPage` model 8c38028964bfb0b8d5a4800a063eaa9acc37e56c

Also removed it from the homepage completely.

Let me know if you're happy for this logic for the release.

Secondly, it's becoming a timesink for me to figure out how to turn off emojicom on Render preview. Would it be ok for me to raise a separate ticket for this?

Thanks 🙏

**Review by plaindocs — APPROVED** [review]
LGTM.

@olyism absolutely, I think that's more of a nice to have than a requirement.

**Comment by olyism** [comment]
Almost forgot to attach cross-browser screenshots. Works on our popular browsers 🖥 ✅

Merging now 🚀

## Chrome

Screen Shot 2022-06-30 at 6 38 15 pm

✅ Does not show on landing pages

Screen Shot 2022-06-30 at 6 38 39 pm

Screen Shot 2022-06-30 at 6 38 55 pm

## Safari

Screen Shot 2022-06-30 at 6 33 05 pm

✅ Does not show on landing pages

Screen Shot 2022-06-30 at 6 35 27 pm

Screen Shot 2022-06-30 at 6 36 41 pm

## Firefox

Screen Shot 2022-06-30 at 6 37 50 pm

✅ Does not show on landing pages

Screen Shot 2022-06-30 at 6 37 23 pm

Screen Shot 2022-06-30 at 6 36 19 pm

## Small screen works too 📱

Screen Shot 2022-06-30 at 6 41 42 pm

Screen Shot 2022-06-30 at 6 41 16 pm

**Pull request merged**
