### PR TITLE
Correct shell command for adding bk apt stuff under debian

### PR DESCRIPTION
**Pull request by plasticine**
As pointed out in slack https://buildkite-community.slack.com/archives/C02T53V9H/p1557363024199300

### CODE REVIEW

**Comment by lox** [comment]
Jinx! https://github.com/buildkite/docs/tree/fix-typo-in-debian-install-instructions

**Comment by plasticine** [comment]
D’oh! 😅

**Comment by plasticine** [comment]
@lox your branch name is better so you win this round! 🤑

**Comment by plasticine** [comment]
@harrietgrace hehe, @lox totally beat me to it in b55105f891ebc09e7e4d6767830e00477f1d3dce!

**Pull request closed without merging**
