### PR TITLE
Add missing “to” in EventBridge docs

### PR DESCRIPTION
**Pull request by toolmantim**
🥫

### CODE REVIEW

**Comment by harrietgrace** [comment]
Any other ones? 😄I'll do a docs bump when you're ready @toolmantim

**Comment by harrietgrace** [comment]
Also, you're off today! Githubbing is illegal on a day off.

**Comment by toolmantim** [comment]
Just the two! I think #646 might have introduced a docs bug in master tho, but perhaps not a blocker.

**Comment by toolmantim** [comment]
Typos on launch day, when scrolling through Twitter, is totes legit 😆

**Pull request merged**
