### PR TITLE
Add `/` as hotkey for search

### PR DESCRIPTION
**Pull request by lachlanhardy**
This resolves DOC-224:
https://linear.app/buildkite/issue/DOC-224/search-box

### CODE REVIEW

**Comment by lachlanhardy** [comment]
@plaindocs Not sure why this one failed to deploy and I don't have the permissions to check. Let me know, though, and I can take a look tonight/tomorrow.

**Comment by plaindocs** [comment]
Looks like

```
       Uglifier::Error: Unexpected token: punc ()). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).

       --

        => window.addEventListener('DOMContentLoaded', () => {

        2   document.onkeyup = (e) => {

        3     const event = window.event || e;

        4 

        5     switch (event.keyCode) {

        6       case 191:

        7         document.getElementById("search").focus();

        8         break;

        9     }

       ==
```

**Comment by lachlanhardy** [comment]
@plaindocs Ah, cheers. I might just revert to ES5.

**Comment by lachlanhardy** [comment]
@plaindocs I went with the ES6 version.

**Review by plaindocs — CHANGES_REQUESTED** [review]
Nice one.

It doesn't work for me (Firefox, Linux)
It does work on Chrome. 

Question: should we implement `/` for the search bar on the landing page? Probably.

**Comment by lachlanhardy** [comment]
Aha! I'll check browsers and add it to the homepage.

**Comment by lachlanhardy** [comment]
@plaindocs This now works in Firefox and appears nicely styled on the homepage. I think you need to re-review here before we can merge

**Review by plaindocs — APPROVED** [review]
Love it!

**Pull request merged**
