### PR TITLE
Add GitHub integration page

### LINKED ISSUE #409: GitHub integrations page
We list GitHub Enterprise in our integrations page. It'd be great to list GitHub (github.com) as well to make it clear that we have integration, and briefly mention what is supported and how to link GitHub and Buildkite accounts. Maybe even a brief note about noreply email handling.

### LINKED ISSUE #472: Documentation for configuring GitHub pipeline rules/settings
While looking at adding builds on forks, @plasticine and I were wondering "Do we have to update the docs if we add a new setting to the "GitHub" section in the pipeline settings. It doesn't look like there's any docs on it.

There's probably a good case for some docs, only because there's some patterns we recommend for common things that are a bit quirky with the way things currently work.

For example, if you only want to run a pipeline on pull requests, you have to set the "Brand filter pattern" on the pipeline to some branch name that will never occur (e.g. "this-branch-will-never-occur"). Pull request builds ignore the branch filter patterns, and all pushes to other branches (e.g. master/stable/beta/etc) will be ignored.

Perhaps it's worth adding a section that explains how to set up various common scenarios/patterns using our settings page as it is today? And down the track we can revisit the way the settings work, and integrate some of the use cases that docs had to help people with.

### PR DESCRIPTION
**Pull request by harrietgrace**
Adding a page for our GitHub integration. As mentioned in  #409 and #472, we've got pages for our other source providers including GitHub enterprise, but nothing for regular GitHub. 

Closes #409 
Closes #472

### CODE REVIEW

**Comment by levicole** [comment]
I may be completely ignorant of the typical flow of getting status checks set up, but this guide would have been super helpful for me about 3 hours ago 😂. Glad to see it's in draft, and that it seems like it's in review!

👍

**Comment by harrietgrace** [comment]
@plaindocs this might be a good PR for you to pick up, if you're looking for something small-ish to do 😄

**Comment by plaindocs** [comment]
Sure thing!

**Comment by plaindocs** [comment]
:-o

**Comment by plaindocs** [comment]
Sorry for the noise folks. Development will continue over in #652.

**Pull request closed without merging**
