### PR TITLE
Layout and visual refinement

### PR DESCRIPTION
**Pull request by BrettJay**
This branch is a companion to #2413 typography uplift design work.

### Full canvas layout, fixed content width
This sets the navigation and grid layout to be full-width, while setting the max-width of page content to the prose width of `712px`, occupying the free space in the center of the viewport between the navigation and table of contents:

<details>
<summary><b>Default docs page layout</b></summary>

CleanShot 2023-08-25 at 06 58 56@2x

</details>

For layouts using the landing page layout, I measured the maximum width the content could previously occupy prior to the typography and this layout branch change (with the previous outer container max-width on the Page grid), and came up with a value of `896px`:

<details>
<summary><b>Test Analytics landing page example</b></summary>

CleanShot 2023-08-25 at 06 59 07@2x
</details>

#### Hyperlink interaction design refinement
Replace svg asset for external link with built-in unicode glyph in font set. Set a fainter text-decoration colour, which becomes fully opaque on hover:

https://github.com/buildkite/docs/assets/677025/be6f99d1-c039-4848-bb14-d032101dacc5

#### Heading anchor interaction design
New interaction design for anchors:

https://github.com/buildkite/docs/assets/677025/d87bc97d-b891-4e7d-b0ec-9baef3499dbf

#### Refined table design

CleanShot 2023-08-25 at 07 14 11@2x

#### Refined Callout design
The previous troubleshooting callout was not accessible on white.

CleanShot 2023-08-25 at 07 13 36@2x

* Specify a background and foreground colour with each callout type, this allows for the note to be more scannable as a callout, with a more accessible text colour.
* We no longer render the corresponding emoji for the callout in the body; instead we use a mono icon from the Hero Icons library that corresponds to the type of callout.
* Typesetting refinements so that the text is always indented to the left from the icon.
* One line callouts no longer appear as if they are missing a title

#### Redesigned responsive-image styling
Rather than padding and a grey border, images are now full-bleed, have a rounded radius applied, and a subtle shadow/outline:

CleanShot 2023-08-25 at 07 17 53@2x

### CODE REVIEW

**Comment by mbelton-buildkite** [comment]
I see this is in draft so I might be jumping the gun, but I think this is looking great! Yay the new callouts and tables! The only thing that I'm not sure about is the inline code background color. It might be a me thing, but I find it a lot harder to read than the existing style.

**Comment by BrettJay** [comment]
@mbelton-buildkite Cheers! Feedback always welcome as I gear up to get this ready for review (Wanted to write a more thorough PR description).

We can certainly tweak the code background colour, would you say the background colour is a little too dark and needs to be fainter against the code text, or the background itself needs to be darker against the white background?

I’ve had a quick go darkening and saturating the element to get it close to `#eeeeee` but saturated with our navy colour temperature (`#e9e9fa`), does this look better/worse in regards to legibility for you? (e.g. does code text need to be darker)

CleanShot 2023-08-24 at 15 05 07@2x

**Comment by mbelton-buildkite** [comment]
> would you say the background colour is a little too dark and needs to be fainter against the code text, or the background itself needs to be darker against the white background?
>
> I’ve had a quick go darkening and saturating the element to get it close to #eeeeee but saturated with our navy colour temperature (#e9e9fa), does this look better/worse in regards to legibility for you? 

I should have been more specific, sorry! I think it was mainly the background against the white. I find the new version much easy to read 😊

**Comment by dannymidnight** [comment]
I am _loving_ these changes @BrettJay.

**Comment by mbelton-buildkite** [comment]
Did something change with the emojicom rendering? I'm seeing it double up when I navigate back to a page on the preview:


https://github.com/buildkite/docs/assets/119824349/0bb614a8-7f60-4265-9259-6ef90da616cd

(Or maybe this is to do with the static preview, @dannymidnight?)

**Comment by dannymidnight** [comment]
> Did something change with the emojicom rendering? I'm seeing it double up when I navigate back to a page on the preview:

Nope, I've seen this before. It's related to the Turbo.

**Comment by mbelton-buildkite** [comment]
> Nope, I've seen this before. It's related to the Turbo.
> 
> I should pop something in our backlog to address it.

I couldn't reproduce the issue on the live site 🤷🏻‍♂️

**Review by mbelton-buildkite — APPROVED** [review]
I still find the inline code harder to read than the previous version (hard on my eyes against the white background), but I'm happy to defer to your expertise. Otherwise, I love all these changes! And thanks for putting in a detailed description. I hadn't noticed the link changes, and love them :)

**Pull request merged**
