### PR TITLE
Remove 'experiment' from output redactor docs

### PR DESCRIPTION
**Pull request by keithduncan**
This will land as default feature in v3.31 so we can remove the experimental caveats from these docs.

@plaindocs should we note the agent minimum version required for the feature anywhere?

### CODE REVIEW

**Comment by plaindocs** [comment]
This is great!

We've not done so much in the past, but especially where the behavior changes like this we should.
The real question is whether we should document both states? I guess because it is experimental we don't commit to that? 
So yeah, :+1: to `introduced in Agent v3.31`

**Comment by plaindocs** [comment]
@StarfallProjects this will affect #1002

**Comment by keithduncan** [comment]
> I guess because it is experimental we don't commit to that?

🤔 I could see including a link to the release that the experiment is available from too, if we’re documenting the experiment it’s probably worth pointing folks to which version they’d need.

> So yeah, 👍 to `introduced in Agent v3.31`

I’ve tried putting this in a new `<p>` tag after the description to see how it looks in the preview deploy, let me know what you think.

**Comment by keithduncan** [comment]
Screenshot 2021-06-16 at 09 18 51

**Comment by toolmantim** [comment]
I wonder if we could put it underneath the name of the config on a new line, rather than in the description? Perhaps just "v3.31 and above" in dark grey?

**Comment by plaindocs** [comment]
@scopegate wanna factor this information design into the parameters rework in #1002 ? 

@toolmantim do you see that needing an introduction of that field for all backwards params? Or starting now for all going forward?

**Comment by keithduncan** [comment]
3.31.0 is live now so this is ready for final review 🙌

**Review by plaindocs — APPROVED** [review]
@keithduncan happy for this to be merged and work on the version tracking stuff separately.

**Pull request merged**
