### PR TITLE
Fix a missing bracket

### PR DESCRIPTION
**Pull request by alastairpat**
Hope you don't mind this absolutely tiny PR but there was a parsing error in my head!

### CODE REVIEW

**Comment by alastairpat** [comment]
Not sure why the build is red - seems unrelated to my change.

**Comment by JuanitoFatas** [comment]
Hi Alastair, thanks for the PR!

Sorry I could be wrong, but the markdown link syntax is `[text](url)`, so there is no missing bracket?

**Comment by plaindocs** [comment]
Tiny fixes always welcome! @JuanitoFatas looks like the fix is to close the 'text' bracket, not the 'markdown' bracket.

**Review by plaindocs — APPROVED** [review]
Thank you!

**Comment by plaindocs** [comment]
And the broken build is unrelated, yes, I'll look into that separately.

**Review by JuanitoFatas — APPROVED** [review]
Ahh I totally miss that, makes sense 👍🏼

**Comment by JuanitoFatas** [comment]
Merged as 26ff0e0. Thanks for your contribution 🙇🏻‍♂️

**Pull request closed without merging**
