### PR TITLE
SUP-2512 | Update pipelines.md

### PR DESCRIPTION
**Pull request by PriyaSudip**
Fixing list_pipelines API response description,

Example response below,

{
    "access_level": "build_and_read",
    "created_at": "2024-07-31T06:21:25.526Z",
    "pipeline_id": "018e9d13-ff7f-456d-ad3b-4f68d0741eb6",
    "pipeline_url": "https://api.buildkite.com/v2/organizations/priya/pipelines/api_test"
  },

### CODE REVIEW

**Comment by gilesgas** [comment]
Hi @PriyaSudip , thanks very much for this contribution! 🎉 

Before merging this PR, there are several other references on this page where the JSON response indicates the following for the `"pipeline_url"` value:

```
"pipeline_url": "http://api.buildkite.com/v2/organizations/acme-inc/pipelines/e5eb97866561b24e088715332a2803dc64f02c61"
```

That is, [here](https://buildkite.com/docs/apis/rest-api/teams/pipelines#get-a-team-pipeline), [here](https://buildkite.com/docs/apis/rest-api/teams/pipelines#create-a-team-pipeline), and [here](https://buildkite.com/docs/apis/rest-api/teams/pipelines#update-a-team-pipeline).

I gather the pipeline slug is now used in all these other cases?

**Review by gilesgas — CHANGES_REQUESTED** [review]
Please address comment above.

**Comment by PriyaSudip** [comment]
> Hi @PriyaSudip , thanks very much for this contribution! 🎉
> 
> Before merging this PR, there are several other references on this page where the JSON response indicates the following for the `"pipeline_url"` value:
> 
> ```
> "pipeline_url": "http://api.buildkite.com/v2/organizations/acme-inc/pipelines/e5eb97866561b24e088715332a2803dc64f02c61"
> ```
> 
> That is, [here](https://buildkite.com/docs/apis/rest-api/teams/pipelines#get-a-team-pipeline), [here](https://buildkite.com/docs/apis/rest-api/teams/pipelines#create-a-team-pipeline), and [here](https://buildkite.com/docs/apis/rest-api/teams/pipelines#update-a-team-pipeline).
> 
> I gather the pipeline slug is now used in the `"pipeline_url"` value for all these other cases? If so, I'll update these other instances as part of this PR and merge it.

Hey @gilesgas , I did a test to confirm the same and it seems all the links you shared have pipeline_slug in the response not UUID. Please go ahead and make the changes.

Get a team pipeline:
image

Create a team pipeline:

image

Update team pipeline:

image

**Review by gilesgas — APPROVED** [review]
Thanks very much @PriyaSudip !

This is now ready for you to merge in :-)

**Pull request merged**
